# Generated by Django 3.2 on 2021-05-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210512_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='Write a brief about yourself here...', max_length=500),
        ),
    ]
